# Configuration for when creating new sensors 

#Elsys_Codec:               -- name of codec in chirpstack/netmore
#  profile_name: elsys      -- profile to use
#  tenant: default          -- tenant to assign device to
#  activate: true           -- activate device upon creation
#  location: true           -- use location from chirpstack/netmore
#  tags: 
#    enabled: true          -- use tags from chirpstack/netmore 
#    metadata: true         -- use tags to create metadata
#    mappings:
#      location: plats      -- map keys. E.g. "location" to "plats"
#      mount: position